const questions = [
  {
    question_text: "What is React?",
    option_a: "A programming language",
    option_b: "A JavaScript library for building user interfaces",
    option_c: "A server-side framework",
    option_d: "A database management system",
    correct_option: "B",
    language: "English",
    difficulty: "easy",
  },
  {
    question_text: "What does JSX stand for in React?",
    option_a: "JavaScript XML",
    option_b: "Java XML",
    option_c: "JSON XML",
    option_d: "JavaScript Extension",
    correct_option: "A",
    language: "English",
    difficulty: "easy",
  },
  {
    question_text: "In React, what is the purpose of the 'state'?",
    option_a: "To store and manage component's internal data",
    option_b: "To handle HTTP requests",
    option_c: "To define styles for components",
    option_d: "To handle routing in the application",
    correct_option: "A",
    language: "English",
    difficulty: "easy",
  },
  {
    question_text: "What is the primary use of Node.js?",
    option_a: "Front-end development",
    option_b: "Server-side development",
    option_c: "Mobile app development",
    option_d: "Database management",
    correct_option: "B",
    language: "English",
    difficulty: "easy",
  },
  {
    question_text: "Which package manager is commonly used with Node.js?",
    option_a: "npm",
    option_b: "Yarn",
    option_c: "Both A and B",
    option_d: "None of the above",
    correct_option: "C",
    language: "English",
    difficulty: "easy",
  },
  {
    question_text:
      "What is the purpose of 'package.json' in a Node.js project?",
    option_a: "To store project configuration",
    option_b: "To manage project dependencies",
    option_c: "To define API routes",
    option_d: "To store CSS styles",
    correct_option: "B",
    language: "English",
    difficulty: "medium",
  },
  {
    question_text: "What is the role of Webpack in a React application?",
    option_a: "To manage server-side logic",
    option_b: "To bundle and optimize JavaScript code",
    option_c: "To handle database connections",
    option_d: "To define API routes",
    correct_option: "B",
    language: "English",
    difficulty: "medium",
  },
  {
    question_text: "What is the main purpose of the 'useEffect' hook in React?",
    option_a: "To handle form submissions",
    option_b: "To perform side effects in functional components",
    option_c: "To define API endpoints",
    option_d: "To create reusable components",
    correct_option: "B",
    language: "English",
    difficulty: "medium",
  },
  {
    question_text: "In Node.js, what is the role of 'npm start' command?",
    option_a: "To install Node modules",
    option_b: "To start the application",
    option_c: "To run tests",
    option_d: "To deploy the application",
    correct_option: "B",
    language: "English",
    difficulty: "medium",
  },
  {
    question_text: "Which of the following is NOT a valid HTTP method?",
    option_a: "GET",
    option_b: "POST",
    option_c: "UPDATE",
    option_d: "DELETE",
    correct_option: "C",
    language: "English",
    difficulty: "medium",
  },
  {
    question_text: "What is the purpose of 'setState' in React?",
    option_a: "To update the DOM directly",
    option_b: "To update the state of a component",
    option_c: "To define CSS styles",
    option_d: "To create a new component",
    correct_option: "B",
    language: "English",
    difficulty: "hard",
  },
  {
    question_text: "Which of the following is a routing library for React?",
    option_a: "Redux",
    option_b: "Express",
    option_c: "React Router",
    option_d: "Axios",
    correct_option: "C",
    language: "English",
    difficulty: "hard",
  },
  {
    question_text: "What is the purpose of the 'require' function in Node.js?",
    option_a: "To include external modules",
    option_b: "To define CSS styles",
    option_c: "To handle database connections",
    option_d: "To create components",
    correct_option: "A",
    language: "English",
    difficulty: "hard",
  },
  {
    question_text: "What is the role of 'middleware' in Express.js?",
    option_a: "To manage server-side logic",
    option_b: "To handle HTTP requests",
    option_c: "To define API routes",
    option_d: "To create authentication checks",
    correct_option: "D",
    language: "English",
    difficulty: "hard",
  },
  {
    question_text: "What does the 'async' keyword indicate in JavaScript?",
    option_a: "It defines an asynchronous function",
    option_b: "It defines a synchronous function",
    option_c: "It handles errors in a try-catch block",
    option_d: "It defines a callback function",
    correct_option: "A",
    language: "English",
    difficulty: "hard",
  },
  {
    question_text: "रिएक्ट क्या है?",
    option_a: "एक प्रोग्रामिंग भाषा",
    option_b: "एक जावास्क्रिप्ट लाइब्रेरी जो यूजर इंटरफेस बनाने के लिए है",
    option_c: "एक सर्वर-साइड फ़्रेमवर्क",
    option_d: "एक डेटाबेस प्रबंधन सिस्टम",
    correct_option: "B",
    language: "Hindi",
    difficulty: "easy",
  },
  {
    question_text: "रिएक्ट में JSX का क्या मतलब है?",
    option_a: "जावास्क्रिप्ट एक्सएमएल",
    option_b: "जावा एक्सएमएल",
    option_c: "जेसन एक्सएमएल",
    option_d: "जावास्क्रिप्ट एक्सटेंशन",
    correct_option: "A",
    language: "Hindi",
    difficulty: "easy",
  },
  {
    question_text: "रिएक्ट में 'स्थिति' का क्या उद्देश्य है?",
    option_a: "कॉम्पोनेंट के आंतरिक डेटा को संग्रहित और प्रबंधित करना",
    option_b: "एचटीटीपी अनुरोधों का संबोधन करना",
    option_c: "कॉम्पोनेंट के लिए शैलियां परिभाषित करना",
    option_d: "एप्लिकेशन में रूटिंग का संबोधन करना",
    correct_option: "A",
    language: "Hindi",
    difficulty: "easy",
  },
  {
    question_text: "Node.js का प्रमुख उपयोग क्या है?",
    option_a: "फ्रंट-एंड डेवेलपमेंट",
    option_b: "सर्वर-साइड डेवेलपमेंट",
    option_c: "मोबाइल एप्लिकेशन डेवेलपमेंट",
    option_d: "डेटाबेस प्रबंधन",
    correct_option: "B",
    language: "Hindi",
    difficulty: "easy",
  },
  {
    question_text:
      "Node.js के साथ सामान्यत: कौन-सा पैकेज मैनेजर उपयोग होता है?",
    option_a: "npm",
    option_b: "Yarn",
    option_c: "दोनों A और B",
    option_d: "इनमें से कोई नहीं",
    correct_option: "C",
    language: "Hindi",
    difficulty: "easy",
  },
  {
    question_text: "Node.js परियोजना में 'package.json' का क्या उद्देश्य है?",
    option_a: "परियोजना कॉन्फ़िगरेशन स्टोर करना",
    option_b: "परियोजना की डिपेंडेंसेज़ को प्रबंधित करना",
    option_c: "API रूट्स को परिभाषित करना",
    option_d: "CSS स्टाइल्स स्टोर करना",
    correct_option: "B",
    language: "Hindi",
    difficulty: "medium",
  },
  {
    question_text: "रिएक्ट एप्लिकेशन में Webpack का क्या कार्य है?",
    option_a: "सर्वर-साइड लॉजिक को प्रबंधित करना",
    option_b: "जावास्क्रिप्ट को बंडल और अनुकूलित करना",
    option_c: "डेटाबेस कनेक्शन को संबोधित करना",
    option_d: "API रूट्स को परिभाषित करना",
    correct_option: "B",
    language: "Hindi",
    difficulty: "medium",
  },
  {
    question_text: "रिएक्ट में 'useEffect' हुक का मुख्य उद्देश्य क्या है?",
    option_a: "फॉर्म सबमिशन का संबोधन करना",
    option_b: "फ़ंक्शनल कॉम्पोनेंट्स में साइड इफेक्ट्स को प्रदान करना",
    option_c: "API एंडपॉइंट्स को परिभाषित करना",
    option_d: "पुनर्निर्माणीय कॉम्पोनेंट्स बनाना",
    correct_option: "B",
    language: "Hindi",
    difficulty: "medium",
  },
  {
    question_text: "Node.js में 'npm start' कमांड का क्या उद्देश्य है?",
    option_a: "नोड मॉड्यूल्स को स्थापित करना",
    option_b: "एप्लिकेशन को शुरू करना",
    option_c: "टेस्ट चलाना",
    option_d: "एप्लिकेशन को डिप्लॉय करना",
    correct_option: "B",
    language: "Hindi",
    difficulty: "medium",
  },
  {
    question_text: "निम्नलिखित में से कौन-सा एक वैध HTTP मेथड नहीं है?",
    option_a: "GET",
    option_b: "POST",
    option_c: "अपडेट",
    option_d: "डिलीट",
    correct_option: "C",
    language: "Hindi",
    difficulty: "medium",
  },
  {
    question_text: "रिएक्ट में 'setState' का क्या उद्देश्य है?",
    option_a: "DOM को सीधे अपडेट करना",
    option_b: "कॉम्पोनेंट की स्थिति को अपडेट करना",
    option_c: "CSS स्टाइल्स की परिभाषा करना",
    option_d: "नए कॉम्पोनेंट बनाना",
    correct_option: "B",
    language: "Hindi",
    difficulty: "hard",
  },
  {
    question_text: "निम्नलिखित में से कौन-सा एक रूटिंग लाइब्रेरी है?",
    option_a: "रीडक्स",
    option_b: "एक्सप्रेस",
    option_c: "रिएक्ट राउटर",
    option_d: "एक्सियोस",
    correct_option: "C",
    language: "Hindi",
    difficulty: "hard",
  },
  {
    question_text: "Node.js में 'require' फ़ंक्शन का क्या कार्य है?",
    option_a: "बाह्य मॉड्यूल्स को शामिल करना",
    option_b: "CSS स्टाइल्स की परिभाषा करना",
    option_c: "डेटाबेस कनेक्शन्स संबोधित करना",
    option_d: "कॉम्पोनेंट्स बनाना",
    correct_option: "A",
    language: "Hindi",
    difficulty: "hard",
  },
  {
    question_text: "एक्सप्रेस.js में 'मिडलवेयर' का क्या कार्य है?",
    option_a: "सर्वर-साइड लॉजिक को प्रबंधित करना",
    option_b: "HTTP अनुरोधों का संबोधन करना",
    option_c: "API रूट्स की परिभाषा करना",
    option_d: "प्रमाणीकरण जाँचें बनाना",
    correct_option: "D",
    language: "Hindi",
    difficulty: "hard",
  },
  {
    question_text: "जावास्क्रिप्ट में 'एसिंक' कीवर्ड का क्या सूचित करता है?",
    option_a: "यह एक एसिंक्रोनस फ़ंक्शन की परिभाषा करता है",
    option_b: "यह एक सिंक्रोनस फ़ंक्शन की परिभाषा करता है",
    option_c: "यह एक ट्राई-कैच ब्लॉक में त्रुटियों को हैंडल करता है",
    option_d: "यह एक कॉलबैक फ़ंक्शन की परिभाषा करता है",
    correct_option: "A",
    language: "Hindi",
    difficulty: "hard",
  },
];

module.exports = questions;
